### ISSUE TITLE
Failed to compile in gcc 4.9

### ISSUE THREAD

**Issue by qubic** [dz0ny/rt8192cu#9]
Failed to compile in gcc 4.9

rt8192cu/os_dep/linux/usb_intf.c:1580:52: error: macro "\_\_DATE\_\_" might prevent reproducible builds [-Werror=date-time]

rt8192cu/os_dep/linux/usb_intf.c:1580:1: error: macro "\_\_TIME\_\_" might prevent reproducible builds [-Werror=date-time]
